name: 'HTTP Remote Deploy'
description: 'Trigger deployment via HTTP Remote API for CI/CD automation'
author: 'pandeptwidyaop'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  remote-url:
    description: 'Base URL of HTTP Remote server (e.g., https://app.example.com)'
    required: true
  app-id:
    description: 'Application UUID from HTTP Remote'
    required: true
  deploy-token:
    description: 'Deploy token for the application'
    required: true
  command-id:
    description: 'Specific command UUID to execute (optional, uses default command if not provided)'
    required: false
    default: ''
  path-prefix:
    description: 'Path prefix configured on server'
    required: false
    default: '/devops'
  wait:
    description: 'Wait for deployment to complete before finishing'
    required: false
    default: 'true'
  timeout:
    description: 'Timeout in seconds when waiting for completion'
    required: false
    default: '600'
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'

outputs:
  execution-id:
    description: 'Execution UUID from HTTP Remote'
    value: ${{ steps.deploy.outputs.execution-id }}
  status:
    description: 'Final deployment status (success/failed/timeout)'
    value: ${{ steps.deploy.outputs.status }}
  exit-code:
    description: 'Command exit code'
    value: ${{ steps.deploy.outputs.exit-code }}
  output:
    description: 'Command output (truncated if too long)'
    value: ${{ steps.deploy.outputs.output }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci --production
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run deployment
      id: deploy
      run: node main.js
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_REMOTE-URL: ${{ inputs.remote-url }}
        INPUT_APP-ID: ${{ inputs.app-id }}
        INPUT_DEPLOY-TOKEN: ${{ inputs.deploy-token }}
        INPUT_COMMAND-ID: ${{ inputs.command-id }}
        INPUT_PATH-PREFIX: ${{ inputs.path-prefix }}
        INPUT_WAIT: ${{ inputs.wait }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
